### ISSUE TITLE
Error de compilación: L_Boton2.h no se encuentra

### ISSUE THREAD

**Issue by electrozeustic** [MeloCuentan/L_Boton2#1]
Buenas tardes. Me da el error de compilación que L_Boton2.h no se encuentra, con el IDE de Arduino.

La solución es renombrar los dos ficheros de la librería y añadirles un "2" al final del nombre antes del punto. Así quedarían: **L_Boton2.h** y **L_Boton2.cpp** para que no dé el error.

Un saludo.

**Comment by MeloCuentan** [comment]
Nombres corregidos!

**Comment by MeloCuentan** [comment]
Gracias por comentarlo para poder corregirlo
