### ISSUE TITLE
¿Posibles rebotes del pulsador?

### ISSUE THREAD

**Issue by electrozeustic** [MeloCuentan/L_Boton2#2]
Buenas noches. He notado algunos valores raros de los que saca el ejemplo (_test.ino_) pero modificado por mí. He usado el siguiente el IDE de Arduino 2.3.2 actualizado en los cores y librerías. Como board usé una ESP32 DevKitC v4 (ESP32 Dev Module) configurada a 240 MHz y un pulsador entre la entrada 18 (pin 18) y el GND de esta board. Los cambios del código (_test.ino_) que he hecho son:

- const uint8_t pinBoton = 18; // Cambio del pin de entrada
- Serial.begin(115200); // Cambio de la velocidad del puerto serie
- // miBoton.variasPulsaciones(intervaloPulsaciones, 2); // Comenté esta línea

El montaje:

![ESP32_Dev_board](https://github.com/MeloCuentan/L_Boton2/assets/85681829/e4551011-0dd5-46bd-98b5-abb62f95cfea)

Entonces, lo que aparece haciendo una sola pulsación, poniendo las marcas temporales en el monitor serie:

![1_pulsacion](https://github.com/MeloCuentan/L_Boton2/assets/85681829/a6893935-3b3e-440a-8428-53ee41fdd900)

Y haciendo una pulsación larga:

![pulsacion_larga](https://github.com/MeloCuentan/L_Boton2/assets/85681829/ec1f44a1-7777-4757-8eea-a0899bf89821)

Podrían ser rebotes al pulsar el botón y al soltarlo.

**Comment by MeloCuentan** [comment]
Buenas noches! 
He hecho unas pequeñas modificaciones para evitar ese error de rebotes en el ESP32. 
Esta vez lo he probado tanto con arduino NANO, como en un ESP32.

**Comment by electrozeustic** [comment]
Buenas tardes,

Sí, parece que funciona bien ahora esa parte.

Pero, en el ejemplo, si descomento la línea de `miBoton.variasPulsaciones(intervaloPulsaciones, 3);` poniendo número máximo de pulsaciones a detectar a 3, por ejemplo, y hago 4, 5,... pulsaciones seguidas "rápidas" me da por el puerto serie, 1, 2 o ninguna pulsación, según como sean las pulsaciones. Me imagino que `intervaloPulsaciones` afectará en esto también. Esto lo dejo como observación por si no lo habías tenido en cuenta.
